# Generated by Django 5.0 on 2024-01-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_product_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
