# Generated by Django 5.0 on 2024-01-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='default_image.jpeg', upload_to='photos/product'),
        ),
    ]
