# Generated by Django 5.0 on 2024-01-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=models.ImageField(default='default_image.jpeg', upload_to='photos/product'),
        ),
    ]
